package com.andre.pe.cpresentacion;


import com.andre.pe.cnegocio.Datos_DocumentoBO;
import com.andre.pe.db.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet; 




public class Datos_Documento extends javax.swing.JPanel{
    
 Datos_DocumentoBO dd = new Datos_DocumentoBO();
 Datos_Documento tdbo = new Datos_Documento();
 

    /**
     * Creates new form Datos_Documento
     */
    public Datos_Documento() {
        initComponents();
        listarDatosDocumento();

       
    }
    public void listarDatosDocumento(){
    dd.listarDatosDocumento(TablaDatosDocumento);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatosDocumento = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        FieldFechaEmision = new javax.swing.JTextField();
        FieldNumero = new javax.swing.JTextField();
        FieldIDCliente = new javax.swing.JTextField();
        FieldFechaVencimiento = new javax.swing.JTextField();
        FieldIDDocumentoIdentidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        FielIDDatosDocumento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 182, 193));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 232, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel1.setText("CRUD DATOS DOCUMENTOS");

        TablaDatosDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 182, 193)));
        TablaDatosDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDatosDocumento.setSelectionBackground(new java.awt.Color(255, 182, 193));
        jScrollPane1.setViewportView(TablaDatosDocumento);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        FieldFechaEmision.setBackground(new java.awt.Color(255, 245, 255));
        FieldFechaEmision.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 182, 193)));
        FieldFechaEmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldFechaEmisionActionPerformed(evt);
            }
        });

        FieldNumero.setBackground(new java.awt.Color(255, 245, 255));
        FieldNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 182, 193)));
        FieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNumeroActionPerformed(evt);
            }
        });

        FieldIDCliente.setBackground(new java.awt.Color(255, 245, 255));
        FieldIDCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 182, 193)));
        FieldIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIDClienteActionPerformed(evt);
            }
        });

        FieldFechaVencimiento.setBackground(new java.awt.Color(255, 245, 255));
        FieldFechaVencimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 182, 193)));

        FieldIDDocumentoIdentidad.setBackground(new java.awt.Color(255, 245, 255));
        FieldIDDocumentoIdentidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 182, 193)));
        FieldIDDocumentoIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldIDDocumentoIdentidadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel2.setText("FECHA DE EMISION:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("NUMERO:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel4.setText("DATOS DOCUMENTO");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel5.setText("FECHA VENCIMIENTO:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel6.setText("ID DOCUMENTO IDENTIDAD:");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        FielIDDatosDocumento.setBackground(new java.awt.Color(255, 245, 255));
        FielIDDatosDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 182, 193)));
        FielIDDatosDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FielIDDatosDocumentoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel7.setText("ID CLIENTE:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FielIDDatosDocumento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldNumero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldFechaEmision, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldFechaVencimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(FieldIDDocumentoIdentidad, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(FieldIDCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLimpiar)
                                .addGap(12, 12, 12)
                                .addComponent(btnGuardar)))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(12, 12, 12)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldIDDocumentoIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FielIDDatosDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void FieldFechaEmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldFechaEmisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldFechaEmisionActionPerformed

    private void FieldIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIDClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIDClienteActionPerformed

    private void FieldIDDocumentoIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldIDDocumentoIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldIDDocumentoIdentidadActionPerformed

    private void FieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNumeroActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
                                           
     String numero = FieldNumero.getText();
    String fechaEmision = FieldFechaEmision.getText();
    String fechaVencimiento = FieldFechaVencimiento.getText();
    String idCliente = FieldIDCliente.getText();
    String idDocumentoIdentidad = FieldIDDocumentoIdentidad.getText();
    
    Connection con = null;
    try {
        con = Conexion.getConnection();
        con.setAutoCommit(false); // Start transaction

        // Check if the client exists
        String checkClienteSql = "SELECT COUNT(*) FROM cliente WHERE id_cliente = ?";
        try (PreparedStatement checkClientePst = con.prepareStatement(checkClienteSql)) {
            checkClientePst.setInt(1, Integer.parseInt(idCliente));
            ResultSet rsCliente = checkClientePst.executeQuery();
            rsCliente.next();
            if (rsCliente.getInt(1) == 0) {
                System.out.println("El cliente con ID " + idCliente + " no existe.");
                return;
            }
        }

        // Check if the identity document exists
        String checkDocIdentidadSql = "SELECT COUNT(*) FROM documento_identidad WHERE id_documento_identidad = ?";
        try (PreparedStatement checkDocIdentidadPst = con.prepareStatement(checkDocIdentidadSql)) {
            checkDocIdentidadPst.setInt(1, Integer.parseInt(idDocumentoIdentidad));
            ResultSet rsDocIdentidad = checkDocIdentidadPst.executeQuery();
            rsDocIdentidad.next();
            if (rsDocIdentidad.getInt(1) == 0) {
                System.out.println("El documento de identidad con ID " + idDocumentoIdentidad + " no existe.");
                return; 
            }
        }

        // Prepare the insert statement
       String sql = "INSERT INTO datos_documento (id_datos_documento, numero, fecha_de_emision, fecha_de_vencimiento, id_cliente, id_documento_identidad) VALUES (datos_documento_seq.NEXTVAL, ?, ?, ?, ?, ?)";

        
        try (PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setInt(1, Integer.parseInt(numero));
            pst.setDate(2, java.sql.Date.valueOf(fechaEmision)); // Ensure the date format is YYYY-MM-DD
            pst.setDate(3, java.sql.Date.valueOf(fechaVencimiento)); // Ensure the date format is YYYY-MM-DD
            pst.setInt(4, Integer.parseInt(idCliente));
            pst.setInt(5, Integer.parseInt(idDocumentoIdentidad));

            pst.executeUpdate();
        }

        con.commit(); // Commit transaction
        System.out.println("Registro guardado correctamente.");

        // Clear fields
        FieldNumero.setText("");
        FieldFechaEmision.setText("");
        FieldFechaVencimiento.setText("");
        FieldIDCliente.setText("");
        FieldIDDocumentoIdentidad.setText("");
        FielIDDatosDocumento.setText("");

    } catch (Exception e) {
        System.out.println("Error al guardar: " + e.getMessage());
        if (con != null) {
            try {
                con.rollback(); // Revert changes on error
            } catch (SQLException rollbackEx) {
                System.out.println("Error al revertir la transacción: " + rollbackEx.getMessage());
            }
        }
    } finally {
        if (con != null) {
            try {
                con.close();
            } catch (SQLException closeEx) {
                System.out.println("Error al cerrar la conexión: " + closeEx.getMessage());
            }
        }
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    FieldNumero.setText(""); // Limpiar el campo de número
    FieldFechaEmision.setText(""); // Limpiar el campo de fecha de emisión
    FieldFechaVencimiento.setText(""); // Limpiar el campo de fecha de vencimiento
    FieldIDCliente.setText(""); // Limpiar el campo de ID de cliente
    FieldIDDocumentoIdentidad.setText(""); // Limpiar el campo de ID de documento de identidad
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void FielIDDatosDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FielIDDatosDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FielIDDatosDocumentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FielIDDatosDocumento;
    private javax.swing.JTextField FieldFechaEmision;
    private javax.swing.JTextField FieldFechaVencimiento;
    private javax.swing.JTextField FieldIDCliente;
    private javax.swing.JTextField FieldIDDocumentoIdentidad;
    private javax.swing.JTextField FieldNumero;
    private javax.swing.JTable TablaDatosDocumento;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
