
package com.andre.pe.cpresentacion;

import com.sun.jdi.connect.spi.Connection;
import javax.swing.*; 
import java.awt.event.*; 
import java.sql.*; 
import com.andre.pe.cnegocio.ClienteBO; 
import com.andre.pe.db.Conexion;
import com.andre.pe.cmodelo.Cliente;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre
 */
public class JFrameCliente extends javax.swing.JPanel {
    ClienteBO tdbo = new ClienteBO() ;

  Cliente dd = new Cliente();

  String ClienteID;

    /**
     * Creates new form Cliente
     */
    

    public JFrameCliente(){
        initComponents();
        listarCliente();

    }
    public void listarCliente (){

    tdbo.listarCliente(TablaSql);

  }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSql = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        FielIDCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FieldApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FieldTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FieldFechaNacimiento = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 232, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel1.setText("CRUD CLIENTE");

        TablaSql.setBackground(new java.awt.Color(255, 245, 255));
        TablaSql.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaSql.setGridColor(new java.awt.Color(255, 245, 255));
        TablaSql.setSelectionBackground(new java.awt.Color(255, 245, 255));
        TablaSql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaSqlMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaSql);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel2.setText("ID CLIENTE");

        FielIDCliente.setBackground(new java.awt.Color(255, 245, 255));
        FielIDCliente.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        FielIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FielIDClienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setText("NOMBRE");

        FieldNombre.setBackground(new java.awt.Color(255, 245, 255));
        FieldNombre.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        FieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setText("APELLIDO");

        FieldApellido.setBackground(new java.awt.Color(255, 245, 255));
        FieldApellido.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel5.setText("EMAIL");

        FieldEmail.setBackground(new java.awt.Color(255, 245, 255));
        FieldEmail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel6.setText("TELEFONO");

        FieldTelefono.setBackground(new java.awt.Color(255, 245, 255));
        FieldTelefono.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel7.setText("FECHA NACIMIENTO");

        FieldFechaNacimiento.setBackground(new java.awt.Color(255, 245, 255));
        FieldFechaNacimiento.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N

        btnEliminar.setBackground(new java.awt.Color(255, 245, 255));
        btnEliminar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 245, 255));
        btnModificar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 245, 255));
        btnGuardar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 245, 255));
        btnLimpiar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(255, 245, 255));
        btnActualizar.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        btnActualizar.setText("Actualizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 209, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar))
                    .addComponent(FielIDCliente)
                    .addComponent(FieldNombre)
                    .addComponent(FieldApellido)
                    .addComponent(FieldEmail)
                    .addComponent(FieldTelefono)
                    .addComponent(FieldFechaNacimiento)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(328, 328, 328))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FielIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnModificar)
                        .addComponent(btnActualizar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnLimpiar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FielIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FielIDClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FielIDClienteActionPerformed

    private void FieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNombreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String idCliente = FielIDCliente.getText();
    String nombre = FieldNombre.getText();
    String apellido = FieldApellido.getText();
    String email = FieldEmail.getText();
    String telefono = FieldTelefono.getText();
    String fechaNacimiento = FieldFechaNacimiento.getText();

    Cliente cliente = new Cliente();
    cliente.setClienteID(Integer.parseInt(idCliente));
    cliente.setNombre(nombre);
    cliente.setApellido(apellido);
    cliente.setEmail(email);
    cliente.setTelefono(telefono);
    cliente.setFechaNacimiento(fechaNacimiento);

    // Usar ClienteBO para la lógica de negocio
    ClienteBO clienteBO = new ClienteBO();
    if (clienteBO.verificarCliente(cliente.getClienteID())) {
        System.out.println("El cliente con ID " + idCliente + " ya existe. Procediendo a actualizar.");
        clienteBO.actualizarCliente(cliente); 
        System.out.println("Cliente actualizado correctamente.");
    } else {
        clienteBO.guardarCliente(cliente);
        System.out.println("Cliente guardado correctamente.");
    }
    FielIDCliente.setText("");
    FieldNombre.setText("");
    FieldApellido.setText("");
    FieldEmail.setText("");
    FieldTelefono.setText("");
    FieldFechaNacimiento.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    FielIDCliente.setText("");      
    FieldNombre.setText("");        
    FieldApellido.setText("");       
    FieldEmail.setText("");          
    FieldTelefono.setText("");      
    FieldFechaNacimiento.setText(""); 
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void TablaSqlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaSqlMouseClicked
      
    int seleccion = TablaSql.rowAtPoint(evt.getPoint());

    ClienteID = TablaSql.getValueAt(seleccion, 0)+"";

     

     

    FieldNombre.setText(TablaSql.getValueAt(seleccion, 1)+"");

    FieldApellido.setText(TablaSql.getValueAt(seleccion, 2)+"");

    FieldEmail.setText(TablaSql.getValueAt(seleccion, 3)+"");

    FieldTelefono.setText(TablaSql.getValueAt(seleccion, 4)+"");

    FieldFechaNacimiento.setText(TablaSql.getValueAt(seleccion, 5)+"");

    System.out.println(seleccion);


    }//GEN-LAST:event_TablaSqlMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (ClienteID != null && !ClienteID.isEmpty()) {

      try {

        // Establecer el ID del documento a eliminar

        dd.setClienteID(Integer.parseInt(ClienteID));

        // Llamar al método de negocio para eliminar el documento

        String mensaje = tdbo.eliminarCliente(dd);


        // Mostrar mensaje de éxito

        JOptionPane.showMessageDialog(this, mensaje);

         

        listarCliente();
        

      } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this, "Error al eliminar: ID no válido.");

      } catch (SQLException e) {

        JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());

      } catch (Exception e) {

        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());

      }

    } else {

      JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para eliminar.");

    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (ClienteID != null && !ClienteID.isEmpty()) {

    try {

      dd.setClienteID(Integer.parseInt(ClienteID));

    dd.setNombre(FieldNombre.getText());
    dd.setApellido(FieldApellido.getText());
    dd.setEmail(FieldEmail.getText());
    dd.setTelefono(FieldTelefono.getText());
    dd.setFechaNacimiento(FieldFechaNacimiento.getText()); 

       

      String mensaje = tdbo.modificarCliente(dd);

       

      JOptionPane.showMessageDialog(this, mensaje);

       

      listarCliente();

       

    } catch (NumberFormatException e) {

      JOptionPane.showMessageDialog(this, "Error: Verifique que todos los campos sean válidos.");

    } catch (SQLException e) {

      JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());

    } catch (Exception e) {

      JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());

    }

  } else {

    JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para modificar.");

  }
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FielIDCliente;
    private javax.swing.JTextField FieldApellido;
    private javax.swing.JTextField FieldEmail;
    private javax.swing.JTextField FieldFechaNacimiento;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTextField FieldTelefono;
    private javax.swing.JTable TablaSql;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
